# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-19 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_dis', models.CharField(max_length=50)),
                ('item_price', models.IntegerField()),
                ('pic', models.ImageField(upload_to='pics')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
