# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-19 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pic',
            field=models.ImageField(upload_to='cafeapp/static/pics'),
        ),
    ]
