# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-19 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0004_auto_20190319_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_dis', models.CharField(max_length=50)),
                ('item_price', models.IntegerField()),
                ('pic', models.ImageField(upload_to='cafeapp/static/pics')),
                ('path', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
