# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-21 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0005_auto_20190319_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usname', models.CharField(max_length=50)),
                ('it_name', models.CharField(max_length=50)),
                ('it_price', models.IntegerField()),
                ('it_quantity', models.IntegerField()),
                ('it_totl', models.IntegerField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
